### ISSUE TITLE
Finish up MVP1

### ISSUE THREAD

**Issue by martonlederer** [useverto/verto#18]
As we are approaching the end of MVP1, we will need to finish up front-end. All the design stuff are almost ready, as well as their implementation in HTML/SASS. Here is the full list about what we need to complete MVP1:

### Implementing and finishing the last designs:
- [x] [Design/develop trading post gallery](https://github.com/t8/coinary-app/issues/16) (@martonlederer @maximousblk)
- [x] Implement confirmation modal design (@martonlederer)
- [x] Arrange links to trading post interface (Right now this is only a route, there are no links to it in the front-end) **[URGENT]**

### Implementing logic
- [x] Show total stake, reputation in `app/post.svelte`
  - Total stake: community.xyz function
  - Reputation: See diagram in trading post repo
- [x] Show assets on `app.svelte`, `app/post.svelte`, `app/trade.svelte`
  - Querying with the tags in tokens.svelte & scanning for wallet addresses with balances
- [x] Show exchanges list (with only 4 items) in `app.svelte`
  - Querying with tags in trading post code
- [x] Show full exchanges list in `app/all-exchanges.svelte` ~with pagination (maybe allow searching)~ with infinite scroll
  - Querying with tags in trading post code
- [x] Show transactions list (with only 5 items) in `app.svelte`
- [x] Show transactions list (with only 5 items) in `app/post.svelte`, relative to the post
  - John can do this
- [x] Show full transactions list in `app/all-transactions.svelte`  ~with pagination (maybe allow searching)~ with infinite scroll
~Show increase / decrease of balance (with for e.g. `(+0.75%)`) in `app.svelte`, `app/post.svelte` **[NOT PRIORITY]**~
~Write docs (cc @t8, i think you should write it, since you understand the mechanics and logics of the full system)~
- [x] Implement logic in [trading post gallery](https://github.com/t8/coinary-app/issues/16)
- [x] Implement trade logic, (+ recommended post dropdown, exchange rate display, etc.)
  - Querying for the correct trading post
    - The trading post can optionally be url parameter
  - Query for user PST balances
  - Verify that user has the funds
  - Only allow AR trading pairs

**This list looks long, but it is actually just some things detailed. We should be able to finish this today and test**

### Some Svelte links that could help
https://svelte.dev/tutorial/writable-stores
https://svelte.dev/tutorial/auto-subscriptions
https://svelte.dev/tutorial/numeric-inputs
https://svelte.dev/tutorial/if-blocks
https://svelte.dev/tutorial/each-blocks
https://svelte.dev/tutorial/await-blocks
https://svelte.dev/tutorial/onmount
https://svelte.dev/tutorial/ondestroy

**Comment by t8** [comment]
### Updated MVP 1 Preparation List

The following list are things that need to be completed ASAP. The users I mention on this list are only recommendations for who to complete what. You do **not** have to complete a task if you feel uncomfortable doing so, but please let somebody know!

#### Styling:

- [trade.svelte] Not selecting a trading post causes a bug when exchanging
  - Recommended to complete: @martonlederer (svelte expertise and squasher of bugs)
- [gallery.svelte] Fix card layout scaling
  - Recommended to complete: @martonlederer (custom sass wizard)

<details>
<summary>Gallery Image example</summary>
<img src="https://user-images.githubusercontent.com/20846869/90997127-ae438a00-e58e-11ea-9c1c-d605d2401f4b.png" />
</details>

- [post.svelte] Fix reputation & total stake positioning (and possibly move the trade now button to a different location for smaller screen sizes? Not a priority)
  - Recommended to complete: @martonlederer (again, sass wizard) & @maximousblk (a UI/UX connoisseur who knows where to strategically place a button for **maximum** efficiency)
￼
<details>
<summary>Post Image example</summary>
<img src="https://user-images.githubusercontent.com/20846869/90997267-15613e80-e58f-11ea-82e7-dc437f4caa20.png" />
</details>

#### Functionality:

- [home/LatestTrades.svelte] Add PST type detection and display correspondingly
  - Recommended to complete: @t8 (hi)
￼
<details>
<summary>LatestTrades Image example</summary>
<img src="https://user-images.githubusercontent.com/20846869/90997331-46da0a00-e58f-11ea-9ecc-9b00f599e727.png" />
</details>

- [app.svelte] Display exchanges & statuses (same algorithm for “View all”)
  - Recommended to complete: @johnletey (very best trackweave-to-english translator) & @zorbyte (the one and only trackweave author & professional code not-tester [this is your opportunity to change the latter title])

<details>
<summary>App Image example</summary>
<img src="https://user-images.githubusercontent.com/20846869/90997379-5f4a2480-e58f-11ea-855a-b2c5449a176d.png" />
</details>

- [trade.svelte] Display all exchanges for a given trading post (need to also differentiate between awaiting match & completed)
  - @johnletey (inferred wanting multiple todos & again, trackweave-to-english translator) & @divy-work (the most savage livesharer of them all)

**Comment by zorbyte** [comment]
;-;
