### ISSUE TITLE
Question: Will verto also support the exchange between ETH & AR ?

### ISSUE THREAD

**Issue by michael-spengler** [useverto/verto#74]
Due to some good progress related to https://gitcoin.co/issue/michael-spengler/wwi18seac/8/100023569 
by https://github.com/soremwar ...
I know some guys who might be interested in contributing a verto based ETH <--> AR Swap feature.

**Comment by t8** [comment]
This would be very interesting to discuss further, but the current infrastructure of the frontend and trading posts strictly supports AR/PSTs.

**Comment by michael-spengler** [comment]
ok cool - let's think about ups and downs of:

Option 1. Providing a dedicated distributed "ETH-AR Swap" 
Option 2. Providing an integrated solution within Verto

I'll raise this topic within: https://discord.gg/TAGvG7

**Comment by michael-spengler** [comment]
The "Ar Swap" app - see bottom of screenshot - seems to be close to working properly - the connect to metamask seems missing.

![Screen Shot 2020-09-17 at 10 36 14 PM](https://user-images.githubusercontent.com/43786652/93666571-a4bf1c00-fa7f-11ea-8944-172a819d5e35.png)
